//
//  WebPageTests.swift
//  DemouiUITests
//
//  Created by Saritha Parsoya on 2/24/24.
//

import XCTest

final class WebPageTests: XCTestCase {

    override func setUpWithError() throws {
        // Put setup code here. This method is called before the invocation of each test method in the class.

        // In UI tests it is usually best to stop immediately when a failure occurs.
        continueAfterFailure = false

        // In UI tests it’s important to set the initial state - such as interface orientation - required for your tests before they run. The setUp method is a good place to do this.
    }

    override func tearDownWithError() throws {
        // Put teardown code here. This method is called after the invocation of each test method in the class.
    }
    
    func testWebURL() throws {
        // UI tests must launch the application that they test.
        let safari = XCUIApplication(bundleIdentifier: "com.apple.mobilesafari")
        safari.launch()
       
    }

    func testExample() throws {
        // UI tests must launch the application that they test.
        let safari = XCUIApplication(bundleIdentifier: "com.apple.mobilesafari")
        safari.launch()
        safari.textFields["Address"].tap()
        
        
        let app = XCUIApplication()
        app.windows["SBSwitcherWindow:Main"].children(matching: .other).element.tap()
        app/*@START_MENU_TOKEN@*/.buttons["ClearTextButton"]/*[[".otherElements[\"SafariWindow?View=Narrow&BarsKeptMinimized=false&UUID=D545CD7A-3D7A-4E22-9DEA-547C1EE43A1B&SupportsTabBar=false&UsingLoweredBar=true&UsingUnifiedBar=false\"]",".otherElements[\"CapsuleViewController\"]",".otherElements[\"CapsuleNavigationBar?isSelected=true\"]",".buttons[\"Clear text\"]",".buttons[\"ClearTextButton\"]"],[[[-1,4],[-1,3],[-1,2,3],[-1,1,2],[-1,0,1]],[[-1,4],[-1,3],[-1,2,3],[-1,1,2]],[[-1,4],[-1,3],[-1,2,3]],[[-1,4],[-1,3]]],[0]]@END_MENU_TOKEN@*/.tap()
        app/*@START_MENU_TOKEN@*/.otherElements["TabDocument?IsLoadedUsingDesktopUserAgent=false&InReaderMode=false&UUID=B236DA5D-6691-45A9-8E5F-4BDD8ED80A3C&IsPrivate=false&IsPageLoaded=true&WebViewProcessID=69497"].webViews["WebView"].webViews.webViews.buttons["Close banner"]/*[[".otherElements[\"SafariWindow?View=Narrow&BarsKeptMinimized=false&UUID=D545CD7A-3D7A-4E22-9DEA-547C1EE43A1B&SupportsTabBar=false&UsingLoweredBar=true&UsingUnifiedBar=false\"]",".scrollViews.otherElements[\"TabDocument?IsLoadedUsingDesktopUserAgent=false&InReaderMode=false&UUID=B236DA5D-6691-45A9-8E5F-4BDD8ED80A3C&IsPrivate=false&IsPageLoaded=true&WebViewProcessID=69497\"].webViews[\"WebView\"].webViews.webViews",".otherElements.matching(identifier: \"Walmart | Save Money. Live better.\").buttons[\"Close banner\"]",".buttons[\"Close banner\"]",".otherElements[\"TabDocument?IsLoadedUsingDesktopUserAgent=false&InReaderMode=false&UUID=B236DA5D-6691-45A9-8E5F-4BDD8ED80A3C&IsPrivate=false&IsPageLoaded=true&WebViewProcessID=69497\"].webViews[\"WebView\"].webViews.webViews"],[[[-1,4,2],[-1,1,2],[-1,0,1]],[[-1,4,2],[-1,1,2]],[[-1,3],[-1,2]]],[0,0]]@END_MENU_TOKEN@*/.tap()
        app/*@START_MENU_TOKEN@*/.otherElements["TabDocument?IsLoadedUsingDesktopUserAgent=false&InReaderMode=false&UUID=B236DA5D-6691-45A9-8E5F-4BDD8ED80A3C&IsPrivate=false&IsPageLoaded=true&WebViewProcessID=69497"].webViews["WebView"].webViews.webViews.staticTexts["Living room updates"]/*[[".otherElements[\"SafariWindow?View=Narrow&BarsKeptMinimized=false&UUID=D545CD7A-3D7A-4E22-9DEA-547C1EE43A1B&SupportsTabBar=false&UsingLoweredBar=true&UsingUnifiedBar=false\"]",".scrollViews.otherElements[\"TabDocument?IsLoadedUsingDesktopUserAgent=false&InReaderMode=false&UUID=B236DA5D-6691-45A9-8E5F-4BDD8ED80A3C&IsPrivate=false&IsPageLoaded=true&WebViewProcessID=69497\"].webViews[\"WebView\"].webViews.webViews",".otherElements.matching(identifier: \"Walmart | Save Money. Live better.\")",".otherElements[\"main\"].staticTexts[\"Living room updates\"]",".staticTexts[\"Living room updates\"]",".otherElements[\"TabDocument?IsLoadedUsingDesktopUserAgent=false&InReaderMode=false&UUID=B236DA5D-6691-45A9-8E5F-4BDD8ED80A3C&IsPrivate=false&IsPageLoaded=true&WebViewProcessID=69497\"].webViews[\"WebView\"].webViews.webViews"],[[[-1,5,2],[-1,1,2],[-1,0,1]],[[-1,5,2],[-1,1,2]],[[-1,4],[-1,3],[-1,2,3]],[[-1,4],[-1,3]]],[0,0]]@END_MENU_TOKEN@*/.swipeUp()
        
        let getInStoreForFreeStaticText = app/*@START_MENU_TOKEN@*/.otherElements["TabDocument?IsLoadedUsingDesktopUserAgent=false&InReaderMode=false&UUID=B236DA5D-6691-45A9-8E5F-4BDD8ED80A3C&IsPrivate=false&IsPageLoaded=true&WebViewProcessID=69497"].webViews["WebView"].webViews.webViews.staticTexts["Get in-store for free*"]/*[[".otherElements[\"SafariWindow?View=Narrow&BarsKeptMinimized=false&UUID=D545CD7A-3D7A-4E22-9DEA-547C1EE43A1B&SupportsTabBar=false&UsingLoweredBar=true&UsingUnifiedBar=false\"]",".scrollViews.otherElements[\"TabDocument?IsLoadedUsingDesktopUserAgent=false&InReaderMode=false&UUID=B236DA5D-6691-45A9-8E5F-4BDD8ED80A3C&IsPrivate=false&IsPageLoaded=true&WebViewProcessID=69497\"].webViews[\"WebView\"].webViews.webViews",".otherElements.matching(identifier: \"Walmart | Save Money. Live better.\")",".otherElements[\"main\"].staticTexts[\"Get in-store for free*\"]",".staticTexts[\"Get in-store for free*\"]",".otherElements[\"TabDocument?IsLoadedUsingDesktopUserAgent=false&InReaderMode=false&UUID=B236DA5D-6691-45A9-8E5F-4BDD8ED80A3C&IsPrivate=false&IsPageLoaded=true&WebViewProcessID=69497\"].webViews[\"WebView\"].webViews.webViews"],[[[-1,5,2],[-1,1,2],[-1,0,1]],[[-1,5,2],[-1,1,2]],[[-1,4],[-1,3],[-1,2,3]],[[-1,4],[-1,3]]],[0,0]]@END_MENU_TOKEN@*/
        getInStoreForFreeStaticText.swipeUp()
        getInStoreForFreeStaticText.swipeDown()
        app/*@START_MENU_TOKEN@*/.otherElements["TabDocument?IsLoadedUsingDesktopUserAgent=false&InReaderMode=false&UUID=B236DA5D-6691-45A9-8E5F-4BDD8ED80A3C&IsPrivate=false&IsPageLoaded=true&WebViewProcessID=69497"].webViews["WebView"].webViews.webViews.searchFields["Search Walmart"]/*[[".otherElements[\"SafariWindow?View=Narrow&BarsKeptMinimized=false&UUID=D545CD7A-3D7A-4E22-9DEA-547C1EE43A1B&SupportsTabBar=false&UsingLoweredBar=true&UsingUnifiedBar=false\"]",".scrollViews.otherElements[\"TabDocument?IsLoadedUsingDesktopUserAgent=false&InReaderMode=false&UUID=B236DA5D-6691-45A9-8E5F-4BDD8ED80A3C&IsPrivate=false&IsPageLoaded=true&WebViewProcessID=69497\"].webViews[\"WebView\"].webViews.webViews",".otherElements.matching(identifier: \"Walmart | Save Money. Live better.\")",".otherElements[\"banner\"]",".otherElements[\"Walmart Site-Wide, search\"].searchFields[\"Search Walmart\"]",".searchFields[\"Search Walmart\"]",".otherElements[\"TabDocument?IsLoadedUsingDesktopUserAgent=false&InReaderMode=false&UUID=B236DA5D-6691-45A9-8E5F-4BDD8ED80A3C&IsPrivate=false&IsPageLoaded=true&WebViewProcessID=69497\"].webViews[\"WebView\"].webViews.webViews"],[[[-1,6,2],[-1,1,2],[-1,0,1]],[[-1,6,2],[-1,1,2]],[[-1,5],[-1,4],[-1,3,4],[-1,2,3]],[[-1,5],[-1,4],[-1,3,4]],[[-1,5],[-1,4]]],[0,0]]@END_MENU_TOKEN@*/.tap()
        app/*@START_MENU_TOKEN@*/.otherElements["TabDocument?IsLoadedUsingDesktopUserAgent=false&InReaderMode=false&UUID=B236DA5D-6691-45A9-8E5F-4BDD8ED80A3C&IsPrivate=false&IsPageLoaded=true&WebViewProcessID=69497"].webViews["WebView"].webViews.webViews.staticTexts["Price when purchased online"]/*[[".otherElements[\"SafariWindow?View=Narrow&BarsKeptMinimized=false&UUID=D545CD7A-3D7A-4E22-9DEA-547C1EE43A1B&SupportsTabBar=false&UsingLoweredBar=true&UsingUnifiedBar=false\"]",".scrollViews.otherElements[\"TabDocument?IsLoadedUsingDesktopUserAgent=false&InReaderMode=false&UUID=B236DA5D-6691-45A9-8E5F-4BDD8ED80A3C&IsPrivate=false&IsPageLoaded=true&WebViewProcessID=69497\"].webViews[\"WebView\"].webViews.webViews",".otherElements[\"boy toys - Walmart.com\"]",".otherElements[\"main\"].staticTexts[\"Price when purchased online\"]",".staticTexts[\"Price when purchased online\"]",".otherElements[\"TabDocument?IsLoadedUsingDesktopUserAgent=false&InReaderMode=false&UUID=B236DA5D-6691-45A9-8E5F-4BDD8ED80A3C&IsPrivate=false&IsPageLoaded=true&WebViewProcessID=69497\"].webViews[\"WebView\"].webViews.webViews"],[[[-1,5,2],[-1,1,2],[-1,0,1]],[[-1,5,2],[-1,1,2]],[[-1,4],[-1,3],[-1,2,3]],[[-1,4],[-1,3]]],[0,0]]@END_MENU_TOKEN@*/.swipeUp()
        app/*@START_MENU_TOKEN@*/.otherElements["TabDocument?IsLoadedUsingDesktopUserAgent=false&InReaderMode=false&UUID=B236DA5D-6691-45A9-8E5F-4BDD8ED80A3C&IsPrivate=false&IsPageLoaded=true&WebViewProcessID=69497"].webViews["WebView"].webViews.webViews.otherElements["main"].children(matching: .other).element(boundBy: 5).children(matching: .other).element(boundBy: 1).children(matching: .staticText)["Ayieyill Basketball Hoop Indoor for Kids 15.7\" x 11.8\" - Automatic Scoring Basketball Hoop Mini Basketball Hoop for Door with 3 Balls, Basketball Toy for Kids Boys Teens Adults"]/*[[".otherElements[\"SafariWindow?View=Narrow&BarsKeptMinimized=false&UUID=D545CD7A-3D7A-4E22-9DEA-547C1EE43A1B&SupportsTabBar=false&UsingLoweredBar=true&UsingUnifiedBar=false\"]",".scrollViews.otherElements[\"TabDocument?IsLoadedUsingDesktopUserAgent=false&InReaderMode=false&UUID=B236DA5D-6691-45A9-8E5F-4BDD8ED80A3C&IsPrivate=false&IsPageLoaded=true&WebViewProcessID=69497\"].webViews[\"WebView\"].webViews.webViews",".otherElements[\"boy toys - Walmart.com\"].otherElements[\"main\"].children(matching: .other).element(boundBy: 5).children(matching: .other).element(boundBy: 1)",".children(matching: .staticText)[\"Ayieyill Basketball Hoop Indoor for Kids 15.7\\\" x 11.8\\\" - Automatic Scoring Basketball Hoop Mini Basketball Hoop for Door with 3 \"]",".children(matching: .staticText)[\"Ayieyill Basketball Hoop Indoor for Kids 15.7\\\" x 11.8\\\" - Automatic Scoring Basketball Hoop Mini Basketball Hoop for Door with 3 Balls, Basketball Toy for Kids Boys Teens Adults\"]",".otherElements[\"main\"].children(matching: .other).element(boundBy: 5).children(matching: .other).element(boundBy: 1)",".otherElements[\"TabDocument?IsLoadedUsingDesktopUserAgent=false&InReaderMode=false&UUID=B236DA5D-6691-45A9-8E5F-4BDD8ED80A3C&IsPrivate=false&IsPageLoaded=true&WebViewProcessID=69497\"].webViews[\"WebView\"].webViews.webViews"],[[[-1,6,2],[-1,1,2],[-1,0,1]],[[-1,6,2],[-1,1,2]],[[-1,5,3],[-1,2,3]],[[-1,4],[-1,3]]],[0,0,0]]@END_MENU_TOKEN@*/.swipeUp()
        app/*@START_MENU_TOKEN@*/.otherElements["TabDocument?IsLoadedUsingDesktopUserAgent=false&InReaderMode=false&UUID=B236DA5D-6691-45A9-8E5F-4BDD8ED80A3C&IsPrivate=false&IsPageLoaded=true&WebViewProcessID=69497"].webViews["WebView"].webViews.webViews.staticTexts["Flash Deal"]/*[[".otherElements[\"SafariWindow?View=Narrow&BarsKeptMinimized=false&UUID=D545CD7A-3D7A-4E22-9DEA-547C1EE43A1B&SupportsTabBar=false&UsingLoweredBar=true&UsingUnifiedBar=false\"]",".scrollViews.otherElements[\"TabDocument?IsLoadedUsingDesktopUserAgent=false&InReaderMode=false&UUID=B236DA5D-6691-45A9-8E5F-4BDD8ED80A3C&IsPrivate=false&IsPageLoaded=true&WebViewProcessID=69497\"].webViews[\"WebView\"].webViews.webViews",".otherElements[\"Ayieyill Basketball Hoop Indoor for Kids 15.7\\\" x 11.8\\\" - Automatic Scoring Basketball Hoop Mini Basketball Hoop for Door with 3 Balls, Basketball Toy for Kids Boys Teens Adults - Walmart.com\"]",".otherElements[\"main\"].staticTexts[\"Flash Deal\"]",".staticTexts[\"Flash Deal\"]",".otherElements[\"TabDocument?IsLoadedUsingDesktopUserAgent=false&InReaderMode=false&UUID=B236DA5D-6691-45A9-8E5F-4BDD8ED80A3C&IsPrivate=false&IsPageLoaded=true&WebViewProcessID=69497\"].webViews[\"WebView\"].webViews.webViews"],[[[-1,5,2],[-1,1,2],[-1,0,1]],[[-1,5,2],[-1,1,2]],[[-1,4],[-1,3],[-1,2,3]],[[-1,4],[-1,3]]],[0,0]]@END_MENU_TOKEN@*/.tap()
        app/*@START_MENU_TOKEN@*/.otherElements["TabDocument?IsLoadedUsingDesktopUserAgent=false&InReaderMode=false&UUID=B236DA5D-6691-45A9-8E5F-4BDD8ED80A3C&IsPrivate=false&IsPageLoaded=true&WebViewProcessID=69497"].webViews["WebView"].webViews.webViews.buttons["Menu"]/*[[".otherElements[\"SafariWindow?View=Narrow&BarsKeptMinimized=false&UUID=D545CD7A-3D7A-4E22-9DEA-547C1EE43A1B&SupportsTabBar=false&UsingLoweredBar=true&UsingUnifiedBar=false\"]",".scrollViews.otherElements[\"TabDocument?IsLoadedUsingDesktopUserAgent=false&InReaderMode=false&UUID=B236DA5D-6691-45A9-8E5F-4BDD8ED80A3C&IsPrivate=false&IsPageLoaded=true&WebViewProcessID=69497\"].webViews[\"WebView\"].webViews.webViews",".otherElements[\"Ayieyill Basketball Hoop Indoor for Kids 15.7\\\" x 11.8\\\" - Automatic Scoring Basketball Hoop Mini Basketball Hoop for Door with 3 Balls, Basketball Toy for Kids Boys Teens Adults - Walmart.com\"]",".otherElements.matching(identifier: \"banner\").buttons[\"Menu\"]",".buttons[\"Menu\"]",".otherElements[\"TabDocument?IsLoadedUsingDesktopUserAgent=false&InReaderMode=false&UUID=B236DA5D-6691-45A9-8E5F-4BDD8ED80A3C&IsPrivate=false&IsPageLoaded=true&WebViewProcessID=69497\"].webViews[\"WebView\"].webViews.webViews"],[[[-1,5,2],[-1,1,2],[-1,0,1]],[[-1,5,2],[-1,1,2]],[[-1,4],[-1,3],[-1,2,3]],[[-1,4],[-1,3]]],[0,0]]@END_MENU_TOKEN@*/.tap()

        // Use XCTAssert and related functions to verify your tests produce the correct results.
    }

}
